---
stages:
  - build

variables:
  IMAGE_NAME: chrislusf/seaweedfs
  VERSION: large_disk-kryptonite-debug
  SEAWEED_VERSION: 3.87

build_image:
  stage: build
  image: docker
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'push'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - export DOCKER_REGISTRY=docker.kryptodev.ru
    - export APP_TAG=${CI_COMMIT_TAG}
    - export IMAGE_TAG=${APP_TAG}_${VERSION}
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASS $DOCKER_REGISTRY
  script:
    - |
      if [[ "${APP_TAG}" == "" ]]; then
        export IMAGE_TAG=${SEAWEED_VERSION}-${CI_COMMIT_SHA}
      fi
    - docker build --no-cache -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -f Dockerfile .
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
  when: manual

